export const GLOSSARY = {
  far:              'Floor Area Ratio — the ratio of a building\'s total floor area to the size of the lot. A FAR of 5 on a 2,000 SF lot allows up to 10,000 SF of building.',
  resFar:           'Max FAR allowed for residential use in this zoning district. Higher FAR = more total square footage you can build.',
  builtFar:         'How much of the allowed FAR is already consumed by the existing building on this lot.',
  availableFar:     'Square footage you can still build: (Allowed FAR − Built FAR) × Lot Area. This is the "unused development right."',
  farUtilization:   'What % of the allowed development density is already used up. Below 50% = significant room to build.',
  opportunityScore: 'Parcel score from 0–100 ranking this lot\'s development potential. Driven by unused FAR, lot size, land use type, and zoning density. 85+ = very high potential.',
  lotArea:          'Total land area of this tax lot in square feet, as recorded in NYC PLUTO.',
  bbl:              'Borough-Block-Lot — NYC\'s unique property identifier. Format: B-BBBBB-LLLL (e.g., 1-00950-0001 = Manhattan, Block 950, Lot 1).',
  maxBuildable:     'Maximum total floor area allowed on this lot under current zoning: Lot Area × Max Residential FAR.',
  unusedFar:        'Available development rights in square feet: the gap between what\'s allowed and what\'s built.',
  assessmentValue:  'NYC\'s assessed value for property tax purposes. Typically well below market value for development sites.',
  yearBuilt:        'Year the existing structure was built, from NYC PLUTO.',
  rentStabilized:   'Buildings built before 1974 with 6+ residential units are likely subject to rent stabilization. Buying out stabilized tenants is complex, time-consuming, and expensive — a major acquisition risk.',
  landmark:         'NYC Landmarks Preservation Commission (LPC) designation. Requires LPC approval for any alterations or demolition. However, unused development rights from landmark lots can often be transferred to adjacent sites (Transferable Development Rights / TDR).',
  dealType:         'Parcel classification of the most likely redevelopment strategy for this site: Vacant (ready to build), Teardown (demolish & replace), Garage/Parking (low-value surface use), Conversion (change of use), or Commercial.',
  landUse:          'NYC\'s official classification of how the property is currently used (One & Two Family, Multi-Family, Commercial, Parking, Vacant, etc.).',
  matching:         'Number of lots currently matching your active filters (deal type, neighborhood, min size, min score). Adjust filters to see more or fewer.',
  estFloors:        'Rough estimate of how many floors you could build, based on Max Buildable SF ÷ Lot Area × 0.9 efficiency factor.',
}
